#!/bin/sh
# Maintainer script for withlinux
set -e

lines=$(sh _bin/stat_lines.sh | tail -n1 | awk '{print $1}' | sed -e 's/\n//g')
files=$(find . -path ./.git -prune -o -name '*.pdf' -prune -o -type f -print | nl | tail -n1 | awk '{print $1}' | sed -e 's/\n//g')
sizes=$(du -sh . | awk '{print $1}' | sed -e 's/\n//g')

Usage () {
printf "%s" "[m"
cat << EOF
usage: $0 <action>
actions:
  scan  scan for files missing in README.md
  stat  statistic lines in all plain files, also dumps all plain files
EOF
echo
printf "Project withlinux has %s%d%s files currently.\n" "[34;1m" $files "[;0m"
printf "Project withlinux has %s%d%s lines currently.\n" "[33;1m" $lines "[;0m"
printf "Project withlinux occupies %s%s%s of disk space.\n" "[36;1m" $sizes "[;0m"
}

# detect arg
if [ -z $1 ]; then
  Usage
  exit 1
fi

# invoke sub scripts
case $1 in
scan)
  exec _bin/scan_missing.sh
  ;;
stat)
  exec _bin/stat_lines.sh
  ;;
help)
  Usage
  ;;
*)
  echo "E: invalid action"
  ;;
esac
